name: Build LLM FX

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 24
      uses: actions/setup-java@v4
      with:
        java-version: '24.0.1'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Archive the JAR file as an artifact      
      uses: actions/upload-artifact@v4
      with:
        name: llm-fx
        path: target/llm-fx-*-runner.jar
